server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
        - id: document-service
          uri: lb://document-service
          predicates:
            - Path=/api/documents/**
        - id: grammar-service
          uri: lb://grammar-service
          predicates:
            - Path=/api/grammar/**
  application:
    name: gateway-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

